version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pandektes
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nestjs-app:  
    build: .
    container_name: nestjs_app
    depends_on:
      - db
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=pandektes
    ports:
      - "3000:3000" 
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

volumes:
  pgdata:
